#!/usr/bin/env python3
"""Generate a stylized robotic-fish mesh as a binary STL.

The fish is built so that its nose points along +x (the body-frame forward
axis used by odom_visualization), it is laterally compressed (taller in z
than wide in y, like a real fish), and it spans roughly 1 unit in length so
that the existing robot_scale=1.0 looks reasonable in rviz.

Pure standard library (struct/math) so it runs anywhere without numpy.
"""
import math
import struct

# ----- tunable geometry -----------------------------------------------------
NOSE_X = 0.55          # tip of the snout
TAIL_X = -0.35         # where the body meets the caudal peduncle
BODY_LEN = NOSE_X - TAIL_X
MAX_HALF_HEIGHT = 0.22  # half body height (z) at the fattest station
MAX_HALF_WIDTH = 0.11   # half body width  (y) at the fattest station
N_STATIONS = 28         # rings along the body
M_AROUND = 18           # vertices around each ring

tris = []  # list of (v0, v1, v2)


def add_quad(a, b, c, d):
    tris.append((a, b, c))
    tris.append((a, c, d))


def profile(t):
    """Radius scale in [0,1] along the body. t=0 nose, t=1 tail base.

    Fattest a bit behind the head, smoothly tapering to a thin peduncle.
    """
    # bell-ish curve peaking around t=0.32
    p = math.sin(math.pi * min(max(t, 0.0), 1.0) ** 0.85)
    # keep a slim but non-zero peduncle at the tail
    return 0.12 + 0.88 * p


# ----- body (lofted elliptical rings) --------------------------------------
rings = []
for i in range(N_STATIONS + 1):
    t = i / N_STATIONS
    x = NOSE_X - t * BODY_LEN
    s = profile(t)
    ring = []
    for j in range(M_AROUND):
        a = 2.0 * math.pi * j / M_AROUND
        y = s * MAX_HALF_WIDTH * math.cos(a)
        z = s * MAX_HALF_HEIGHT * math.sin(a)
        ring.append((x, y, z))
    rings.append(ring)

# stitch consecutive rings
for i in range(N_STATIONS):
    r0, r1 = rings[i], rings[i + 1]
    for j in range(M_AROUND):
        k = (j + 1) % M_AROUND
        add_quad(r0[j], r0[k], r1[k], r1[j])

# cap the nose and the tail base with simple fans
nose_tip = (NOSE_X + 0.02, 0.0, 0.0)
for j in range(M_AROUND):
    k = (j + 1) % M_AROUND
    tris.append((nose_tip, rings[0][k], rings[0][j]))

tail_center = (TAIL_X, 0.0, 0.0)
for j in range(M_AROUND):
    k = (j + 1) % M_AROUND
    tris.append((tail_center, rings[-1][j], rings[-1][k]))

# ----- caudal (tail) fin: flat vertical forked fin -------------------------
fin_root_x = TAIL_X
fin_tip_x = TAIL_X - 0.28
lobe_z = 0.30
notch_x = TAIL_X - 0.12

cf = [
    (fin_root_x, 0.0, 0.06),    # 0 upper root
    (fin_root_x, 0.0, -0.06),   # 1 lower root
    (fin_tip_x, 0.0, lobe_z),   # 2 upper lobe tip
    (fin_tip_x, 0.0, -lobe_z),  # 3 lower lobe tip
    (notch_x, 0.0, 0.0),        # 4 central notch
]
# build the two lobes (double-sided so it shows from both faces)
for a, b, c in [(0, 2, 4), (1, 4, 3)]:
    tris.append((cf[a], cf[b], cf[c]))
    tris.append((cf[a], cf[c], cf[b]))

# ----- dorsal fin: flat triangle along the back ----------------------------
df = [
    (0.18, 0.0, MAX_HALF_HEIGHT * 0.9),
    (-0.18, 0.0, MAX_HALF_HEIGHT * 0.85),
    (-0.02, 0.0, MAX_HALF_HEIGHT + 0.18),
]
tris.append((df[0], df[1], df[2]))
tris.append((df[0], df[2], df[1]))

# ----- pectoral fins: small flat side fins ---------------------------------
for sign in (1.0, -1.0):
    pf = [
        (0.18, sign * MAX_HALF_WIDTH * 0.8, -0.02),
        (0.02, sign * MAX_HALF_WIDTH * 0.8, -0.04),
        (0.06, sign * (MAX_HALF_WIDTH + 0.16), -0.12),
    ]
    tris.append((pf[0], pf[1], pf[2]))
    tris.append((pf[0], pf[2], pf[1]))


def normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    L = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return (nx / L, ny / L, nz / L)


def write_stl(path):
    with open(path, "wb") as f:
        f.write(b"robotic-fish stylized mesh generated by make_fish.py".ljust(80, b"\0"))
        f.write(struct.pack("<I", len(tris)))
        for a, b, c in tris:
            n = normal(a, b, c)
            f.write(struct.pack("<3f", *n))
            for v in (a, b, c):
                f.write(struct.pack("<3f", *v))
            f.write(struct.pack("<H", 0))


if __name__ == "__main__":
    out = "fish.stl"
    write_stl(out)
    print("wrote %s with %d triangles" % (out, len(tris)))
